In [5]:
# 1. Load dataset and produce a "data quality report": 
# count of nulls per column, duplicate rows, data type issues, value range anomalies

import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("D:/OIBSIP/DataAnalytics-L1Task3-CleaningData/netflix1.csv")
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [7]:
df.shape

(8790, 10)

In [8]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [9]:
df.eq("Not Given").sum()

show_id            0
type               0
title              0
director        2588
country          287
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.dtypes

show_id           str
type              str
title             str
director          str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
dtype: object

In [12]:
df["date_added"]=pd.to_datetime(df["date_added"], errors="coerce")

In [13]:
df["dt_year"] = df["date_added"].dt.year

In [14]:
df[["date_added", "dt_year"]].head()

  date_added  dt_year
0 2021-09-25     2021
1 2021-09-24     2021
2 2021-09-24     2021
3 2021-09-22     2021
4 2021-09-24     2021

In [15]:
df.describe()

                       date_added  release_year      dt_year
count                        8790   8790.000000  8790.000000
mean   2019-05-17 21:44:01.638225   2014.183163  2018.873606
min           2008-01-01 00:00:00   1925.000000  2008.000000
25%           2018-04-06 00:00:00   2013.000000  2018.000000
50%           2019-07-03 00:00:00   2017.000000  2019.000000
75%           2020-08-19 18:00:00   2019.000000  2020.000000
max           2021-09-25 00:00:00   2021.000000  2021.000000
std                           NaN      8.825466     1.573568

In [16]:
# 2. missing data handiling values
df = df.replace("Not Given", np.nan)

In [17]:
df["director"] = df["director"].fillna("Unknown")

In [18]:
df["country"] = df["country"].fillna("Unknown")

In [19]:
df["date_added"] = pd.to_datetime(
    df["date_added"],
    errors="coerce"
)
df["date_added"].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-22
4   2021-09-24
Name: date_added, dtype: datetime64[us]

In [20]:
df = df.dropna(subset=["date_added"])
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in,dt_year
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,2021
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",2021
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",2021
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",2021
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",2021

In [21]:
# 3. duplicate Removal
duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)

df = df.drop_duplicates()
print("Rows after removing duplicates:", len(df))


df = df.replace("Not Given", np.nan)
print("Missing values after converting 'Not Given':")
display(df.isnull().sum().to_frame("Missing Count"))

before = df["director"].isnull().sum()
df["director"] = df["director"].fillna("Unknown")

after = df["director"].isnull().sum()
print("Director missing values BEFORE:", before)
print("Director missing values AFTER:", after)

Duplicate rows: 0
Rows after removing duplicates: 8790
Missing values after converting 'Not Given':

              Missing Count
show_id                   0
type                      0
title                     0
director                  0
country                   0
date_added                0
release_year              0
rating                    0
duration                  0
listed_in                 0
dt_year                   0

Director missing values BEFORE: 0
Director missing values AFTER: 0

In [22]:
# 4. Standardisation

df["type"] = df["type"].replace({
    "movie": "Movie",
    "tv show": "TV Show",
    "TV show": "TV Show"
})
df["type"].value_counts()

type
Movie      6126
TV Show    2664
Name: count, dtype: int64

In [23]:
df["show_id"] = df["show_id"].astype("string")

df["type"] = df["type"].astype("string")

df["title"] = df["title"].astype("string")

df["director"] = df["director"].astype("string")

df["country"] = df["country"].astype("string")

df["rating"] = df["rating"].astype("string")

df["duration"] = df["duration"].astype("string")

df["listed_in"] = df["listed_in"].astype("string")

df["release_year"] = pd.to_numeric(
    df["release_year"],
    errors="coerce"
).astype("Int64")

In [24]:
df["show_id"] = df["show_id"].astype("string")

df["type"] = df["type"].astype("string")

df["title"] = df["title"].astype("string")

df["director"] = df["director"].astype("string")

df["country"] = df["country"].astype("string")

df["rating"] = df["rating"].astype("string")

df["duration"] = df["duration"].astype("string")

df["listed_in"] = df["listed_in"].astype("string")

df["release_year"] = pd.to_numeric(
    df["release_year"],
    errors="coerce"
).astype("Int64")

print("Corrected data types:")
display(df.dtypes.to_frame("Data Type"))

Corrected data types:

                   Data Type
show_id               string
type                  string
title                 string
director              string
country               string
date_added    datetime64[us]
release_year           Int64
rating                string
duration              string
listed_in             string
dt_year                int32

In [25]:
# 8.Outlier Detection: use IQR method or Z-score to identify outliers in numeric columns; decide and document whether to cap, remove, or retain each
duration_parts = df["duration"].str.extract(r"^\s*(\d+)\s*(min|mins|Season|Seasons)\s*$")
df["duration_value"] = pd.to_numeric(duration_parts[0],errors="coerce")
df["duration_unit"] = duration_parts[1].replace({"mins": "min","Seasons": "Season"})
display(df[["duration", "duration_value", "duration_unit"]].head(10))

    duration  duration_value duration_unit
0     90 min              90           min
1   1 Season               1        Season
2   1 Season               1        Season
3     91 min              91           min
4    125 min             125           min
5  9 Seasons               9        Season
6    104 min             104           min
7     87 min              87           min
8    127 min             127           min
9     76 min              76           min

In [26]:
# IQR FOR DURATION VALUE
Q1 = df["duration_value"].quantile(0.25)
Q3 = df["duration_value"].quantile(0.75)

IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df["duration_value"] < lower_bound) |
    (df["duration_value"] > upper_bound)
]
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("Number of Outliers:", len(outliers))

Q1: 2.0
Q3: 106.0
IQR: 104.0
Lower Bound: -154.0
Upper Bound: 262.0
Number of Outliers: 2

In [27]:
#decesion of whether to cap, remove, or retain each.
#The IQR method was used to identify potential outliers. The detected values were reviewed as potential domain-valid observations. 
#Extreme release years and long movie durations can represent legitimate Netflix titles rather than data-entry errors. 
#Therefore, the outliers were retained instead of being capped or removed. This prevents loss of valid information and avoids distorting the dataset.

In [28]:
# Data type correction: ensure all columns have the correct dtype (e.g., dates as datetime, IDs as string, monetary values as float)

summary = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Duplicate Count",
        "Null Count"
    ],
    "Before Cleaning": [
        len(df),
        int(df.duplicated().sum()),
        int(df.isnull().sum().sum())
    ],
    "After Cleaning": [
        len(df),
        int(df.duplicated().sum()),
        int(df.isnull().sum().sum())
    ]
})

display(summary)

            Metric  Before Cleaning  After Cleaning
0        Row Count             8790            8790
1  Duplicate Count                0               0
2       Null Count                0               0

In [29]:
expected_dtypes = {
    "show_id": "string",
    "type": "string",
    "title": "string",
    "director": "string",
    "country": "string",
    "date_added": "datetime64[ns]",
    "release_year": "Int64",
    "rating": "string",
    "duration": "string",
    "listed_in": "string"}

dtype_accuracy = sum(
    str(df[column].dtype) == expected
    for column, expected in expected_dtypes.items())

print("Correct dtypes:", dtype_accuracy, "/ 10")

Correct dtypes: 9 / 10

In [30]:
# BEFORE CLEANING

before_rows = len(df)
before_duplicates = int(df.duplicated().sum())
before_nulls = int(df.isnull().sum().sum())

print("BEFORE CLEANING")
print("Row Count:", before_rows)
print("Duplicate Count:", before_duplicates)
print("Null Count:", before_nulls)

BEFORE CLEANING
Row Count: 8790
Duplicate Count: 0
Null Count: 0

In [31]:
# AFTER CLEANING

after_rows = len(df)
after_duplicates = int(df.duplicated().sum())
after_nulls = int(df.isnull().sum().sum())

print("AFTER CLEANING")
print("Row Count:", after_rows)
print("Duplicate Count:", after_duplicates)
print("Null Count:", after_nulls)

AFTER CLEANING
Row Count: 8790
Duplicate Count: 0
Null Count: 0

In [32]:
# Produce a "before vs. after" summary table: null count, duplicate count, row count, and dtype accuracy — before and after cleaning

summary = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Duplicate Count",
        "Null Count"
    ],
    "Before Cleaning": [
        before_rows,
        before_duplicates,
        before_nulls
    ],
    "After Cleaning": [
        after_rows,
        after_duplicates,
        after_nulls
    ]
})

display(summary)

            Metric  Before Cleaning  After Cleaning
0        Row Count             8790            8790
1  Duplicate Count                0               0
2       Null Count                0               0

In [35]:
#Save the cleaned dataset to a new CSV file
df.to_csv("netflix1_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")
print("File: D:/OIBSIP/DataAnalytics-L1Task3-CleaningData/netflix1_cleaned.csv")

Cleaned dataset saved successfully!
File: D:/OIBSIP/DataAnalytics-L1Task3-CleaningData/netflix1_cleaned.csv